MODEL:
  PRETRAIN_PATH: '/export/home/dongshichao/.torch/models/resnet50-19c8e357.pth'


INPUT:
#  SIZE_TRAIN: [128, 64]
  SIZE_TRAIN: [256, 128]
#  SIZE_TRAIN: [360, 180]
#  SIZE_TRAIN: [288, 144]
#  SIZE_TEST: [288, 144]
#  SIZE_TEST: [360, 180]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
#   NAMES: ('cuhk03')
#   NAMES: ('dukemtmc')
   NAMES: ('market1501')
#   NAMES: ('msmt17')
DATALOADER:
  SAMPLER: 'multiple_softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 32

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 320
  BASE_LR: 0.00036
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  # STEPS: [40, 70]
  STEPS: [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40 
  LOG_PERIOD: 100
  EVAL_PERIOD: 40 

TEST:
  IMS_PER_BATCH: 256
  WEIGHT: '/home/dongshichao/Dsc/D_paper/reid_baseline-master/Sugger/2020/LBNNeck_v2-256x128/duke-0.03/resnet50_model_320.pth'
# OUTPUT_DIR: "/home/dongshichao/Dsc/D_paper/reid_baseline-master/Sugger/songcy/BNNeck/ChannelSplit6/gcb_ch/market1501"
OUTPUT_DIR: "/home/dongshichao/Dsc/D_paper/reid_baseline-master/Sugger/SuggerNet/result/market1501/baseline_GCB_LBN10_1010"
